---
title: "BRBC WQTC - Figure Generation"
output: html_document
date: "2024-03-20"
author: "Eric Camm (City of Calgary), Cecilia Chung (Alberta Environment & Protected Areas)"
description: "Code to generate three figures for each station/parameter combination - (1) flow over time, (2) concentration over time, (3) flux over time."
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 1) Prepare R Environment

```{r}
# (A) ONLY WHEN NEEDED: CLEAN UP WORKSPACE-----
rm(list=ls())

# (B) LOAD PACKAGES-----

## Run line below if you don't have pacman installed already
# install.packages('pacman')
pacman::p_load(reshape2, janitor, tidyverse)

# (C) LOAD FUNCTIONS-----

## (C.1) Generate percentiles of historical data -----
### (source: Eric Camm) 
### To use: 
### percentile_station(dataset, cut-off year, variable name, site name)

percentile_station <- function(data, max, parameter, site) {

  historical_range <- data %>%
    filter(variable_name == parameter) %>%
    filter(WQTC_StationName.x == site) %>%
    filter(YEAR != max) %>%
    filter(is.na(measurement_value) != TRUE)

  perc_distribution <- ecdf(historical_range$measurement_value)

  all_year <- data %>%
    filter(variable_name == parameter) %>%
    filter(WQTC_StationName.x == site) %>%
    group_by(station, variable_name, YEAR) %>% # group by year to generate percentiles for each year
    summarize(avg = median(measurement_value)) %>% # comparing median against percentiles, could also use mean here
    mutate(perc_bin = perc_distribution(avg))

  return(all_year)
}

# generate percentile bins for plotting
# either base::cut or santoku::chop work here
df_all$colourcut <- cut(df_all$perc_bin, breaks = c(0, 0.1, 0.25, 0.75, 0.90, 1))


## (C.2) Plot function to to graph percentile outputs -----
### (source: Eric Camm)
### TO USE:
### plot_site("BOW RIVER, AT CLUNY")

plot_site <- function(site) {
  df_all %>%
    filter(station == site) %>%
    ggplot(aes(
      x = year, y = measurement_value, group = year,
      fill = colourcut
    )) +
    geom_boxplot() +
    # stat_summary(fun = "mean",col='red',geom='point') + #to add mean data point to plots
    scale_y_log10() +
    facet_wrap(~variable_name, scales = "free") +
    labs(
      title = site,
      subtitle = "Water Quality Percentile Comparisons",
      y = "log10(measurement_value)", x = ""
    ) +
    scale_fill_manual(
      name = "Percentile",
      values = c("#1f26f5", "#55d7da", "#1df129", "#e9ad29", "#b34044", NA),
      drop = FALSE, # need this argument to keep unused categories
      labels = c("<10th", "10th - 24th", "25th - 75th", "76th - 90th", ">90th", "Not ranked")
    ) +
    theme_bw()
}

# (D) ESTABLISH FILEPATHS-----
path.plot <- paste0("M:/OPS/SSR/South/Exchange/Limnology/Cecilia/BRBC/WQ Technical Committee/figs")


```

### 2) Load and Prepare Datasets

```{r}
# (A) CONSOLIDATED SWQ-FLOW DATASET -----
## from Eric Camm & Nadine Taube
df <-read_csv(file.choose(), na=c("", "NA")) %>%
  filter(variable_name != "TEMPERATURE WATER")

### TODO there appears to be duplicate rows - can we remove?

# (B) ESTABLISH PARAMETERS -----
maxyr = 2022 # cut-off year

selectstn <-unique(df$WQTC_StationName.x)
selectvar <-unique(df$variable_name)

### select only stations where there is flow data
flow_availability <- df %>%
  group_by(WQTC_StationName.x) %>%
  summarise(non_NA_count = sum(!is.na(daily.flow.cms)))
flow_availability_nonNA <- flow_availability %>%
  filter(non_NA_count >0)
selectflowstn <- unique(flow_availability_nonNA$WQTC_StationName.x)

### exclude turbidity, pH, SpCond for flux calculations
selectfluxvar <-c("CHLORIDE DISSOLVED",
                  "SULPHATE DISSOLVED",
                  "OXYGEN DISSOLVED (FIELD METER)",
                  "NITROGEN TOTAL (CALCD.)",
                  "TOTAL DISSOLVED SOLIDS (CALCD.)",
                  "CARBON TOTAL ORGANIC (TOC)",
                  "NITROGEN, NITRATE",
                  "AMMONIA TOTAL",
                  "ESCHERICHIA COLI", # different flux calculation
                  "PHOSPHORUS TOTAL (P)",
                  "PHOSPHORUS TOTAL DISSOLVED")

# (C) CALCULATE FLUX -----
### concentration (mg/L) x discharge (cms)
### e.g. for variables other than E.coli, 
### (mg/L * 0.001 L/m3) * (m3/s * 86400 s/d) = 
### (mg/m3) * (m3/d) = 
### (mg/d)

df.flux <- df %>%
  filter(variable_name %in% selectfluxvar) %>%
  filter(variable_name !="ESCHERICHIA COLI") %>% # remove E.coli because different calc - see below
  mutate(flux = (measurement_value*0.001)*(daily.flow.cms*86400),
         flux_unit = "mg/d")

### for E.coli, 
### (count/100mL * 0.1 mL/L * 0.001 L/m3) * (m3/s * 86400 s/d) = 
### (count/m3) * (m3/d) = 
### (count/d)

df.flux.Ecoli <- df %>%
  filter(variable_name == "ESCHERICHIA COLI") %>%
  mutate(flux = (measurement_value*0.1*0.001)*(daily.flow.cms*86400),
         flux_unit = "No/d") # sometimes MPN/day....do we care?

### join flux calculations back into df
df.flux <- bind_rows(df.flux, df.flux.Ecoli)
df <- left_join(df, df.flux[,c(4:6,14,17,25,26)], by=c("sample_date", "variable_name", "measurement_value", "WQTC_StationName.x", "daily.flow.cms"))


# (D) CALCULATE PERCENTILE BINS (CONC) -----
# loop percentiles function over all parameters and stations

df.percbin = NULL
for (i in selectstn){
  for (j in selectvar){
    
    subdf <- df %>%
      filter(WQTC_StationName.x == i) %>%
      filter(variable_name == j) %>%
      filter(YEAR != maxyr) %>%
      filter(is.na(measurement_value) != TRUE)
    
    perc_distribution <- ecdf(subdf$measurement_value)
    
    df.percbin.new <- subdf %>%
      group_by(WQTC_StationName.x, variable_name, YEAR) %>% # group by year to generate percentiles for each year
      summarize(avg = median(measurement_value)) %>% # comparing median against percentiles, could also use mean here
      mutate(perc_bin = perc_distribution(avg)) %>%
      mutate(colourcut = cut(perc_bin, breaks = c(0, 0.1, 0.25, 0.75, 0.90, 1))) # generate percentile bins for plotting
    
    # add it to df.percbin
    df.percbin <-bind_rows(df.percbin, df.percbin.new)
    
  }
}

## join df.percbin with df
df.all <-left_join(df, df.percbin, by=c("WQTC_StationName.x", "variable_name", "YEAR"))

```

### 3) Generate Figures

```{r}
# (A) FIGURE: FLOW -----
for (i in selectflowstn){ # only do for stations that have flow data
  
  # subset data
  df.p.flow <-df %>% subset(WQTC_StationName.x==i & variable_name==j)
  
  p.flow <-ggplot(data=df.p.flow, aes(x=MONTH_YEAR, y=daily.flow.cms)) +
    geom_line() +
    scale_x_date(date_breaks="1 year", date_labels="%Y") +
    labs(title="Flow Data",
         subtitle=i,
         y ="Daily Averaged Flow (cms)",
         x = "Year") +
    theme_bw() +
    theme(axis.text.x = element_text(face="bold", angle = 90, vjust = 0.5, hjust=1),
          axis.text.y = element_text(face="bold"))
  
  # export figure
  ggsave(plot=p.flow, path=path.plot, filename=paste0(i,  "_flow.jpeg"))

}

# (B) FIGURE: CONCENTRATION -----

for (i in selectstn){
  for (j in selectvar){
    
    df.p.conc <- df.all %>%
      filter(WQTC_StationName.x == i) %>%
      filter(variable_name == j) %>%
      filter(YEAR != maxyr)
    
    p.conc <- ggplot(df.p.conc, aes(x = MONTH_YEAR, y = measurement_value, group = YEAR, fill = colourcut)) +
      geom_boxplot() +
      # stat_summary(fun = "mean",col='red',geom='point') + #to add mean data point to plots
      scale_y_log10() +
      scale_x_date(date_breaks="1 year", date_labels="%Y") +
      labs(
        title = i,
        subtitle = "Water Quality Percentile Comparisons : Concentration",
        y = paste0("log10(",j,")"), 
        x = ""
        ) +
      scale_fill_manual(
        name = "Percentile",
        values = c("#1f26f5", "#55d7da", "#1df129", "#e9ad29", "#b34044", NA),
        drop = FALSE, # need this argument to keep unused categories
        labels = c("<10th", "10th - 24th", "25th - 75th", "76th - 90th", ">90th", "Not ranked")
        ) +
      theme_bw() +
      theme(axis.text.x = element_text(face="bold", angle = 90, vjust = 0.5, hjust=1),
            axis.text.y = element_text(face="bold"))
    
    # export figure
    ggsave(plot=p.conc, path=path.plot, filename=paste0(i,  "_conc.jpeg"))
    
  }
}

# (C) FIGURE: FLUX -----

for (i in selectflowstn){ # only stations with flow
  for (j in selectfluxvar){ # only variables in concentrations
    
    df.p.flux <- df.all %>%
      filter(WQTC_StationName.x == i) %>%
      filter(variable_name == j) %>%
      filter(YEAR != maxyr)
    
    p.flux <- ggplot(df.p.flux, aes(x = MONTH_YEAR, y = flux, group = YEAR, fill = colourcut)) +
      geom_boxplot() +
      # stat_summary(fun = "mean",col='red',geom='point') + #to add mean data point to plots
      scale_y_log10() +
      scale_x_date(date_breaks="1 year", date_labels="%Y") +
      labs(
        title = i,
        subtitle = "Water Quality Percentile Comparisons : Flux",
        y = paste0("log10(",j,")"), 
        x = ""
        ) +
      scale_fill_manual(
        name = "Percentile",
        values = c("#1f26f5", "#55d7da", "#1df129", "#e9ad29", "#b34044", NA),
        drop = FALSE, # need this argument to keep unused categories
        labels = c("<10th", "10th - 24th", "25th - 75th", "76th - 90th", ">90th", "Not ranked")
        ) +
      theme_bw() +
      theme(axis.text.x = element_text(face="bold", angle = 90, vjust = 0.5, hjust=1),
            axis.text.y = element_text(face="bold"))
    
    # export figure
    ggsave(plot=p.conc, path=path.plot, filename=paste0(i,  "_flux.jpeg"))
    
  }
}

```